# Generated by Django 4.2.21 on 2025-06-02 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('status', models.CharField(choices=[('running', '运行中'), ('completed', '已完成'), ('failed', '失败')], default='running', max_length=20, verbose_name='状态')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('total_count', models.IntegerField(default=0, verbose_name='总数量')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功数量')),
                ('error_log', models.TextField(blank=True, verbose_name='错误日志')),
            ],
            options={
                'verbose_name': '爬虫日志',
                'verbose_name_plural': '爬虫日志',
                'db_table': 'crawler_logs',
            },
        ),
        migrations.CreateModel(
            name='QAData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='问题')),
                ('answer', models.TextField(verbose_name='答案')),
                ('source', models.CharField(default='丁香医生', max_length=100, verbose_name='来源')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='分类')),
                ('keywords', models.TextField(blank=True, help_text='JSON格式存储', verbose_name='关键词')),
                ('processed_question', models.TextField(blank=True, verbose_name='处理后的问题')),
                ('processed_answer', models.TextField(blank=True, verbose_name='处理后的答案')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '问答数据',
                'verbose_name_plural': '问答数据',
                'db_table': 'qa_data',
            },
        ),
        migrations.CreateModel(
            name='TextMiningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=200, verbose_name='数据集名称')),
                ('file_path', models.FileField(upload_to='datasets/', verbose_name='数据集文件')),
                ('clustering_result', models.TextField(blank=True, verbose_name='聚类结果')),
                ('tsne_plot', models.ImageField(blank=True, null=True, upload_to='plots/', verbose_name='t-SNE图')),
                ('wordcloud_plots', models.TextField(blank=True, help_text='JSON格式存储多个词云图路径', verbose_name='词云图路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文本挖掘结果',
                'verbose_name_plural': '文本挖掘结果',
                'db_table': 'text_mining_results',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('file_path', models.FileField(blank=True, upload_to='documents/', verbose_name='文件路径')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='文件类型')),
                ('pos_tags', models.TextField(blank=True, verbose_name='词性标注结果')),
                ('entities', models.TextField(blank=True, verbose_name='实体识别结果')),
                ('summary', models.TextField(blank=True, verbose_name='文档摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '文档',
                'verbose_name_plural': '文档',
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='会话ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '聊天会话',
                'verbose_name_plural': '聊天会话',
                'db_table': 'chat_sessions',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('user', '用户'), ('bot', '机器人')], max_length=10, verbose_name='发送者类型')),
                ('message_type', models.CharField(choices=[('text', '文本'), ('image', '图像')], default='text', max_length=10, verbose_name='消息类型')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_images/', verbose_name='图像')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间戳')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='qa_system.chatsession', verbose_name='会话')),
            ],
            options={
                'verbose_name': '聊天消息',
                'verbose_name_plural': '聊天消息',
                'db_table': 'chat_messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
