# Generated by Django 5.2.1 on 2025-06-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa_system", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageRecognitionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_name",
                    models.CharField(max_length=200, verbose_name="图像名称"),
                ),
                (
                    "image_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="recognition_images/",
                        verbose_name="图像文件",
                    ),
                ),
                (
                    "extracted_text",
                    models.TextField(blank=True, verbose_name="识别出的文本"),
                ),
                (
                    "recognition_details",
                    models.TextField(
                        blank=True,
                        help_text="JSON格式存储OCR详细结果",
                        verbose_name="识别详情",
                    ),
                ),
                (
                    "analysis_result",
                    models.TextField(
                        blank=True,
                        help_text="JSON格式存储文本分析结果",
                        verbose_name="分析结果",
                    ),
                ),
                (
                    "processing_time",
                    models.FloatField(default=0.0, verbose_name="处理时间(秒)"),
                ),
                (
                    "confidence_score",
                    models.FloatField(default=0.0, verbose_name="平均置信度"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "图像识别结果",
                "verbose_name_plural": "图像识别结果",
                "db_table": "image_recognition_results",
                "ordering": ["-created_at"],
            },
        ),
    ]
